# Generated by Django 5.2.3 on 2025-07-02 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0002_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="category_rate",
            new_name="category",
        ),
    ]
