# Generated by Django 5.2.3 on 2025-07-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0004_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="sam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("msg", models.TextField()),
            ],
        ),
    ]
