# Generated by Django 5.2.3 on 2025-07-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0005_sam"),
    ]

    operations = [
        migrations.CreateModel(
            name="userregister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=1000)),
                ("Email", models.EmailField(max_length=254)),
                ("Password", models.CharField(max_length=1000)),
            ],
        ),
    ]
