# Generated by Django 5.2.3 on 2025-07-05 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0006_userregister"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userregister",
            old_name="Email",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="userregister",
            old_name="Name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="userregister",
            old_name="Password",
            new_name="password",
        ),
    ]
