# Generated by Django 5.2.3 on 2025-07-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0007_rename_email_userregister_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=1000)),
            ],
        ),
    ]
