# Generated by Django 5.2.3 on 2025-07-06 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0008_log"),
    ]

    operations = [
        migrations.DeleteModel(
            name="log",
        ),
    ]
