# Generated by Django 5.2.3 on 2025-07-12 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0012_cart_payment_id_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="shippingaddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("phoneno", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=20)),
                ("state", models.CharField(max_length=20)),
                ("pincode", models.CharField(max_length=10)),
                ("email", models.CharField(max_length=30)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myApp.userregister",
                    ),
                ),
            ],
        ),
    ]
