# Generated by Django 5.2.3 on 2025-07-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0013_shippingaddress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingaddress",
            name="phoneno",
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="phone",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="address",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="country",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="state",
            field=models.CharField(max_length=100),
        ),
    ]
