# Generated by Django 5.2.3 on 2025-07-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0014_remove_shippingaddress_phoneno_shippingaddress_phone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="paymentdetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("ShippingAddress", models.TextField()),
            ],
        ),
    ]
