# Generated by Django 5.2.3 on 2025-07-14 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0015_paymentdetail"),
    ]

    operations = [
        migrations.DeleteModel(
            name="paymentdetail",
        ),
    ]
