# Generated by Django 5.2.3 on 2025-07-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0018_alter_order_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="contactus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Email", models.EmailField(max_length=254)),
                ("Message", models.TextField()),
                ("Phonenumber", models.CharField(max_length=30)),
            ],
        ),
    ]
