# Generated by Django 5.2.3 on 2025-07-17 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0019_contactus"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactus",
            old_name="Email",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="contactus",
            old_name="Message",
            new_name="message",
        ),
        migrations.RenameField(
            model_name="contactus",
            old_name="Name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="contactus",
            old_name="Phonenumber",
            new_name="phonenumber",
        ),
    ]
